default:
  image: "ruby:${RUBY_VERSION}"

cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v
  - bundle install -j $(nproc) --path vendor

test:
  script:
    - bundle exec rake test
  parallel:
    matrix:
      - RUBY_VERSION: [ "2.7", "3.0", "3.1" ]

rubocop:
  script:
    - bundle exec rubocop
  variables:
    RUBY_VERSION: "2.7"
